name: V2 - macOS

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: macos-26
            name: macOS 26 (Apple Silicon)

          - image: macos-15
            name: macOS 15 (Apple Silicon)

          - image: macos-15-intel
            name: macOS 15 (Intel)

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies (via brew)
        run: |
          brew install catch2 boost-python3 robin-map nanobind pytest numpy

      - name: Configure project
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DJRL_CMAKEMODULES_BUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Install project
        run: cmake --install build --prefix ./install

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
