name: V2 - Windows

on: [push, pull_request]

permissions:
  packages: write

env:
  USERNAME: ${{ github.actor }}
  VCPKG_COMMAND: C:/vcpkg/vcpkg.exe --vcpkg-root=C:/vcpkg
  FEED_URL: https://nuget.pkg.github.com/${{ github.actor }}/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.actor }}/index.json,readwrite"

jobs:
  windows-with-vcpkg:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-2022
            name: Windows Server 2022
            arch: x64

          - image: windows-2025
            name: Windows Server 2025
            arch: x64

          - image: windows-11-arm
            name: Windows 11 ARM64
            arch: arm64

    steps:
      - uses: actions/checkout@v6
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_COMMAND }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          .$(${{ env.VCPKG_COMMAND }} fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Install C++ dependencies (via vcpkg)
        run: |
          ${{ env.VCPKG_COMMAND }} install catch2 boost-python

      - name: Install Python dependencies (via pip)
        run: |
          C:/vcpkg/installed/${{ matrix.arch }}-windows/tools/python3/python.exe -m ensurepip --upgrade
          C:/vcpkg/installed/${{ matrix.arch }}-windows/tools/python3/python.exe -m pip install nanobind pytest numpy

      - name: Configure project
        run: cmake -G Ninja -S v2 -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PYTHON_BINDINGS=ON -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Install project
        run: cmake --install build --prefix ./install

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
